name: build-raspbian

on:
  workflow_dispatch:

jobs:
  build-raspbian:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the builder
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./debian.Dockerfile
          load: true
          tags: cgx-build:latest
      - name: Build Package
        run: |
          docker image inspect cgx-build
          docker run --rm -v `pwd`:/output cgx-build /bin/bash -c 'cross-build-start && fakeroot-tcp debian/rules binary && cp ../*.deb /output && cross-build-end'
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: debs-raspbian
          path: |
            *.deb
