name: build-raspbian

on:
  workflow_dispatch:

jobs:
  build-raspbian:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.0.3
        id: buildx
        with:
          install: true
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the builder
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./raspbian.Dockerfile
          load: true
          tags: cgx-build-raspbian:latest
      - name: Build Package
        run: |
          docker image inspect cgx-build-raspbian
          docker run --rm -v `pwd`:/output cgx-build-raspbian /bin/bash -c 'cross-build-start && fakeroot-tcp debian/rules binary && cp ../*.deb /output && cross-build-end'
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: debs-raspbian
          path: |
            *.deb
