name: build-ubuntu

on:
  workflow_dispatch:

jobs:
  build-ubuntu:
    strategy:
      matrix:
        arch: [linux/amd64, linux/arm64]
        os: ["20.04", "18.04", "16.04"]
    runs-on: ubuntu-20.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.0.3
        id: buildx
        with:
          install: true
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the builder
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          load: true
          platforms: ${{matrix.arch}}
          tags: cgx-build:latest
          build-args: |
            UBUNTU_VERSION=${{ matrix.os }}
      - name: Build Package
        run: |
          docker run --rm -v `pwd`:/output cgx-build /bin/bash -c 'fakeroot-tcp debian/rules binary && cp ../*.deb /output'
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: debs-ubuntu-${{matrix.os}}
          path: |
            *.deb
